### ISSUE TITLE
mcmc

### ISSUE THREAD

**Issue by zyx125186** [zhilizheng/SBayesRC#20]
![mcmc](https://github.com/zhilizheng/SBayesRC/assets/75961564/ace5f465-b62b-415a-a3f2-8523654c2765)

Why does MCMC iteration encounter this situation？

**Comment by zhilizheng** [comment]
Hi @zyx125186 ,

Could you share us more information?   e.g., what's your input.  It could due to the trait basically have no genetic components, first 200 iteration will assume the trait has, so from the prior, it rejected the assumption in the iterations afterward.  Finally, the model is sure, there is no such components.  

So, without the context, we can't diagnosis whether it's right or not. 

Regards,
Zhili
