### ISSUE TITLE
Parallelism across chromosomes

### ISSUE THREAD

**Issue by ebechor** [zhilizheng/SBayesRC#22]
Hello,

In the computational time section, it is estimated that SBayesRC takes:
 
>7 million SNPs with 96 annotation, estimated 8.5 hours, 74GB memory

Is it possible to run SBayesRC one chromosome at a time, so that it can be run as independent jobs?

Thank you!

**Comment by zhilizheng** [comment]
Hi @ebechor,

I think you can run in this way if you don't have enough resources.  We run those jointly, because the prediction accuracy is higher in some cases, and the parameter estimation looks more reasonable.  But you need to fix the LD folder manually, to put the each block into seperate folder, and set the block index start from 1 and re-base the StartSnpIdx, EndSnpIdx.  I may offer an option in the future. 

Regards,
Zhili
