### ISSUE TITLE
question regarding (effective) sample size

### ISSUE THREAD

**Issue by NienkeMekkes** [zhilizheng/SBayesRC#33]
Dear authors,

Thank you for the great tool! I have one question that I couldn't find the answer to.
I have a summary stat file with a column describing the effective sample size per SNP. I believe I read that real sample size is preferred to effective sample size, is that correct?

I also have the total (real) sample size, but not per individual SNP. Would you advise to use either the real total sample size, or the effective sample size per SNP?

Thank you

**Comment by zhilizheng** [comment]
Hi @NienkeMekkes ,

The per-SNP sample size is prefered in most cases.  The sample size is not euqal in most cases, due to the presented missingness in most data.  Per-SNP sample size would result in smaller model misspecification if it's the correct value. 

Hope this is helpful to your project. 

Regards,
Zhili

**Comment by NienkeMekkes** [comment]
Perfect, thank you! also many thanks for the fast reply
